
services:
  bot:
    container_name: csz-bot
    restart: unless-stopped
    build: .
    volumes:
      - ./config.json:/app/config.json:ro
      - ./aoc.config.json:/app/aoc.config.json:ro
      - ./sounds:/app/sounds:ro
      - ./banners:/app/banners:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./storage.db:/app/storage.db
      - ./logs:/app/logs
