name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - './github/**'
      - './devcontainer/**'
      - README.md
      - CONTRIBUTING.md
      - LICENSE

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    concurrency: production
    environment:
      name: Production

    if: ${{ !github.event.repository.fork }}

    steps:
    - name: Deploy CSZ Bot
      uses: appleboy/ssh-action@029f5b4aeeeb58fdfe1410a5d17f967dacf36262
      env:
        DOCKER_BUILDKIT: 1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        envs: DOCKER_BUILDKIT
        script: /home/csc/deploy.sh
