name: CI

on:
  pull_request:
    branches: [ master ]

env:
  DOCKER_BUILDKIT: "1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build . -t csz-bot:latest

    - name: update configuration
      run: |
        cp .github/config.json config.json
        sed -i 's/<BOT_TOKEN>/${{ secrets.CI_BOT_TOKEN }}/g' config.json
        sed -i 's/<CLIENT_ID>/${{ secrets.CI_CLIENT_ID }}/g' config.json

    - name: start se bot
      run: |
        docker run -v "$PWD/config.json:/app/config.json" csz-bot:latest --dry-run
