name: CI

on:
  pull_request:
    branches: [ master ]

env:
  DOCKER_BUILDKIT: "1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build . -t csz-bot:latest
